package de.unipotsdam.rulegenerator.ontology;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Wed Jul 16 14:45:16 CEST 2014 by tobias
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#LearningUnit
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNIT.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNIT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#LearningUnit"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#AudioOutputAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AUDIOOUTPUTAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_AUDIOOUTPUTAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#AudioOutputAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#CurrentLearningUnitMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLEARNINGUNITMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLEARNINGUNITMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#CurrentLearningUnitMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#DisplayHorizontalResolutionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISPLAYHORIZONTALRESOLUTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_DISPLAYHORIZONTALRESOLUTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#DisplayHorizontalResolutionMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#DisplayVerticalResolutionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISPLAYVERTICALRESOLUTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_DISPLAYVERTICALRESOLUTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#DisplayVerticalResolutionMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#ExpectedTimeNeededForCompletionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXPECTEDTIMENEEDEDFORCOMPLETIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_EXPECTEDTIMENEEDEDFORCOMPLETIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#ExpectedTimeNeededForCompletionMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#ExternalDisplayAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXTERNALDISPLAYAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_EXTERNALDISPLAYAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#ExternalDisplayAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#MicrophoneAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MICROPHONEAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_MICROPHONEAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#MicrophoneAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#PhotoCameraAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHOTOCAMERAAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PHOTOCAMERAAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#PhotoCameraAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#PrinterAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRINTERAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PRINTERAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#PrinterAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#PrintingInkContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRINTINGINKCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_PRINTINGINKCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#PrintingInkContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#RestrictLocationTrackingConstraintHead
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESTRICTLOCATIONTRACKINGCONSTRAINTHEAD.<p>
     * 
     */
    public static final OWLClass CLASS_RESTRICTLOCATIONTRACKINGCONSTRAINTHEAD = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#RestrictLocationTrackingConstraintHead"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#RestrictNavigationTypeConstraintHead
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESTRICTNAVIGATIONTYPECONSTRAINTHEAD.<p>
     * 
     */
    public static final OWLClass CLASS_RESTRICTNAVIGATIONTYPECONSTRAINTHEAD = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#RestrictNavigationTypeConstraintHead"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#UserCurrentLearningStyleInputMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEINPUTMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEINPUTMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#UserCurrentLearningStyleInputMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#UserCurrentLearningStylePerceptionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEPERCEPTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEPERCEPTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#UserCurrentLearningStylePerceptionMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#UserCurrentLearningStyleProcessingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEPROCESSINGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEPROCESSINGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#UserCurrentLearningStyleProcessingMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#UserCurrentLearningStyleUnderstandingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEUNDERSTANDINGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEUNDERSTANDINGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#UserCurrentLearningStyleUnderstandingMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/motivate.owl#VideoCameraAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VIDEOCAMERAAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_VIDEOCAMERAAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#VideoCameraAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#AppointmentDetailContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class APPOINTMENTDETAILCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_APPOINTMENTDETAILCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#AppointmentDetailContextParameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ConstraintHead
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONSTRAINTHEAD.<p>
     * 
     */
    public static final OWLClass CLASS_CONSTRAINTHEAD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ConstraintHead"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ConstraintTail
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONSTRAINTTAIL.<p>
     * 
     */
    public static final OWLClass CLASS_CONSTRAINTTAIL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ConstraintTail"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ContextClass
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTCLASS.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTCLASS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ContextClass"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ContextInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ContextInformationParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTINFORMATIONPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTINFORMATIONPARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ContextInformationParameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentAirPressureMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTAIRPRESSUREMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTAIRPRESSUREMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentAirPressureMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentAmbientNoiseMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTAMBIENTNOISEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTAMBIENTNOISEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentAmbientNoiseMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentAppointmentMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTAPPOINTMENTMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTAPPOINTMENTMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentAppointmentMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentHumidityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTHUMIDITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTHUMIDITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentHumidityMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentLuminosityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLUMINOSITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLUMINOSITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentLuminosityMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentTemperatureMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AKTUELLE_TEMPERATUR.<p>
     * 
     */
    public static final OWLClass CLASS_AKTUELLE_TEMPERATUR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentTemperatureMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentTimeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTTIMEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTTIMEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentTimeMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentlyRainingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLYRAININGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLYRAININGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentlyRainingMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentlySunnyMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLYSUNNYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLYSUNNYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#CurrentlySunnyMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#DateFormatContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATEFORMATCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_DATEFORMATCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#DateFormatContextParameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#DeviceTypeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GERÄTE_TYP.<p>
     * 
     */
    public static final OWLClass CLASS_GERÄTE_TYP = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#DeviceTypeMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#DistanceUnitContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISTANCEUNITCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_DISTANCEUNITCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#DistanceUnitContextParameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#FinishedLearningUnitMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ABGESCHLOSSENE_LERNEINHEIT.<p>
     * 
     */
    public static final OWLClass CLASS_ABGESCHLOSSENE_LERNEINHEIT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#FinishedLearningUnitMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#HasScreenReaderFunctionalityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BIETET_SCREENREADER_FUNKTIONALITÄT.<p>
     * 
     */
    public static final OWLClass CLASS_BIETET_SCREENREADER_FUNKTIONALITÄT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#HasScreenReaderFunctionalityMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#IntervalConstraintTail
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INTERVALCONSTRAINTTAIL.<p>
     * 
     */
    public static final OWLClass CLASS_INTERVALCONSTRAINTTAIL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#IntervalConstraintTail"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#LatitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LATITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LATITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#LatitudeContextParameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#LearningUnitIDContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNITIDCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNITIDCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#LearningUnitIDContextParameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#LocationContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOCATIONCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_LOCATIONCONTEXT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#LocationContext"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#LocationContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOCATIONCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_LOCATIONCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#LocationContextInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#LongitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LONGITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LONGITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#LongitudeContextParameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#MeasurableContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEASURABLECONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_MEASURABLECONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#MeasurableContextInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#MixedContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MIXEDCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_MIXEDCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#MixedContextInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#NextAppointmentMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NEXTAPPOINTMENTMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_NEXTAPPOINTMENTMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#NextAppointmentMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ParameterizedContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARAMETERIZEDCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PARAMETERIZEDCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ParameterizedContextInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#PersonalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSONALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_PERSONALCONTEXT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#PersonalContext"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#PersonalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSONALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PERSONALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#PersonalContextInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#PhysicalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHYSICALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_PHYSICALCONTEXT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#PhysicalContext"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#PhysicalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHYSICALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PHYSICALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#PhysicalContextInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#PressureUnitContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRESSUREUNITCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_PRESSUREUNITCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#PressureUnitContextParameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RankingConstraintTail
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RANKINGCONSTRAINTTAIL.<p>
     * 
     */
    public static final OWLClass CLASS_RANKINGCONSTRAINTTAIL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RankingConstraintTail"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RestrictAudioPlaybackConstraintHead
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESTRICTAUDIOPLAYBACKCONSTRAINTHEAD.<p>
     * 
     */
    public static final OWLClass CLASS_RESTRICTAUDIOPLAYBACKCONSTRAINTHEAD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RestrictAudioPlaybackConstraintHead"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RestrictContentConstraintHead
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESTRICTCONTENTCONSTRAINTHEAD.<p>
     * 
     */
    public static final OWLClass CLASS_RESTRICTCONTENTCONSTRAINTHEAD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RestrictContentConstraintHead"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RestrictDataCaptureConstraintHead
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESTRICTDATACAPTURECONSTRAINTHEAD.<p>
     * 
     */
    public static final OWLClass CLASS_RESTRICTDATACAPTURECONSTRAINTHEAD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RestrictDataCaptureConstraintHead"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RestrictRelationsConstraintHead
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESTRICTRELATIONSCONSTRAINTHEAD.<p>
     * 
     */
    public static final OWLClass CLASS_RESTRICTRELATIONSCONSTRAINTHEAD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RestrictRelationsConstraintHead"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RestrictUsageConstraintHead
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESTRICTUSAGECONSTRAINTHEAD.<p>
     * 
     */
    public static final OWLClass CLASS_RESTRICTUSAGECONSTRAINTHEAD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RestrictUsageConstraintHead"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RestrictVideoPlaybackConstraintHead
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESTRICTVIDEOPLAYBACKCONSTRAINTHEAD.<p>
     * 
     */
    public static final OWLClass CLASS_RESTRICTVIDEOPLAYBACKCONSTRAINTHEAD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#RestrictVideoPlaybackConstraintHead"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ScenarioContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCENARIOCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_SCENARIOCONTEXT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ScenarioContext"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ScenarioContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCENARIOCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_SCENARIOCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#ScenarioContextInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#SituationalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITUATIONALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_SITUATIONALCONTEXT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#SituationalContext"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#SituationalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITUATIONALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_SITUATIONALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#SituationalContextInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TargetLatitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BREITENGRAD_DES_ZIELORTES.<p>
     * 
     */
    public static final OWLClass CLASS_BREITENGRAD_DES_ZIELORTES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TargetLatitudeContextParameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TargetLongitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LÄNGENGRAD_DES_ZIELORTES.<p>
     * 
     */
    public static final OWLClass CLASS_LÄNGENGRAD_DES_ZIELORTES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TargetLongitudeContextParameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TargetTimestampContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TARGETTIMESTAMPCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TARGETTIMESTAMPCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TargetTimestampContextParameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TechnicalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TECHNICALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_TECHNICALCONTEXT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TechnicalContext"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TechnicalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TECHNICALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_TECHNICALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TechnicalContextInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TemperatureScaleContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPERATURESCALECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPERATURESCALECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TemperatureScaleContextParameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TimeUntilTimestampMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TIMEUNTILTIMESTAMPMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_TIMEUNTILTIMESTAMPMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#TimeUntilTimestampMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserDestinationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERDESTINATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERDESTINATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserDestinationMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserDidArriveAtLocationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BENUTZER_IST_AN_POSITION_ANGEKOMMEN.<p>
     * 
     */
    public static final OWLClass CLASS_BENUTZER_IST_AN_POSITION_ANGEKOMMEN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserDidArriveAtLocationMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserDidLeaveLocationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BENUTZER_HAT_POSITION_VERLASSEN.<p>
     * 
     */
    public static final OWLClass CLASS_BENUTZER_HAT_POSITION_VERLASSEN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserDidLeaveLocationMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserIsAtLocationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BENUTZER_BEFINDET_SICH_AN_POSITION.<p>
     * 
     */
    public static final OWLClass CLASS_BENUTZER_BEFINDET_SICH_AN_POSITION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserIsAtLocationMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationAddressMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AKTUELLE_ADRESSE_DES_BENUTZERS.<p>
     * 
     */
    public static final OWLClass CLASS_AKTUELLE_ADRESSE_DES_BENUTZERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationAddressMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationBuildingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GEBÄUDE_IN_DEM_SICH_DER_BENUTZER_BEFINDET.<p>
     * 
     */
    public static final OWLClass CLASS_GEBÄUDE_IN_DEM_SICH_DER_BENUTZER_BEFINDET = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationBuildingMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationCountryMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LAND_IN_DEM_SICH_DER_BENUTZER_BEFINDET.<p>
     * 
     */
    public static final OWLClass CLASS_LAND_IN_DEM_SICH_DER_BENUTZER_BEFINDET = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationCountryMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationDistanceMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENTFERNUNG_DES_BENUTZERS_ZU_EINER_POSITION.<p>
     * 
     */
    public static final OWLClass CLASS_ENTFERNUNG_DES_BENUTZERS_ZU_EINER_POSITION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationDistanceMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationLatitudeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AKTUELLER_BREITENGRAD_DES_BENUTZERS.<p>
     * 
     */
    public static final OWLClass CLASS_AKTUELLER_BREITENGRAD_DES_BENUTZERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationLatitudeMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationLongitudeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AKTUELLER_LÄNGENGRAD_DES_BENUTZERS.<p>
     * 
     */
    public static final OWLClass CLASS_AKTUELLER_LÄNGENGRAD_DES_BENUTZERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationLongitudeMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationRegionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AKTUELLE_POSITION_DES_BENUTZERS.<p>
     * 
     */
    public static final OWLClass CLASS_AKTUELLE_POSITION_DES_BENUTZERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserLocationRegionMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserMeansOfTransportationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FORTBEWEGUNGSMITTEL_DES_BENUTZERS.<p>
     * 
     */
    public static final OWLClass CLASS_FORTBEWEGUNGSMITTEL_DES_BENUTZERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserMeansOfTransportationMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserMovementSpeedMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FORTBEWEGUNGSGESCHWINDIGKEIT_DES_BENUTZERS.<p>
     * 
     */
    public static final OWLClass CLASS_FORTBEWEGUNGSGESCHWINDIGKEIT_DES_BENUTZERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserMovementSpeedMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserRoleMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERROLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERROLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#UserRoleMeasurableInformation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#VelocityUnitContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VELOCITYUNITCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_VELOCITYUNITCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#VelocityUnitContextParameter"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasAlternative
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASALTERNATIVE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASALTERNATIVE = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasAlternative"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasBasis
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBASIS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBASIS = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasBasis"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasContextInformation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTINFORMATION = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasContextInformation"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasExtension
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASEXTENSION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASEXTENSION = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasExtension"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasHelp
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASHELP.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASHELP = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasHelp"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasPrerequisite
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPREREQUISITE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPREREQUISITE = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasPrerequisite"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasReference
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASREFERENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASREFERENCE = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasReference"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasRelation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRELATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRELATION = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasRelation"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasVersion
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASVERSION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASVERSION = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasVersion"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isBasisOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISBASISOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISBASISOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isBasisOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isContextInformationOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTINFORMATIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTINFORMATIONOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isContextInformationOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isExtensionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISEXTENSIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISEXTENSIONOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isExtensionOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isHelpOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISHELPOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISHELPOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isHelpOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isPrerequisiteOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPREREQUISITEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPREREQUISITEOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isPrerequisiteOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isReferenceOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISREFERENCEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISREFERENCEOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isReferenceOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isVersionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISVERSIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISVERSIONOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isVersionOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/motivate.owl#isConstraintTailOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONSTRAINTTAILOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONSTRAINTTAILOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#isConstraintTailOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/motivate.owl#isMeasurableContextInformationOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISMEASURABLECONTEXTINFORMATIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISMEASURABLECONTEXTINFORMATIONOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#isMeasurableContextInformationOf"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasConstraintTail
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONSTRAINTTAIL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONSTRAINTTAIL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasConstraintTail"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasContextClass
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTCLASS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTCLASS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasContextClass"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasContextInformationParameter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTINFORMATIONPARAMETER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTINFORMATIONPARAMETER = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasContextInformationParameter"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasMeasurableContextInformation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMEASURABLECONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMEASURABLECONTEXTINFORMATION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasMeasurableContextInformation"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#isContextClassOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTCLASSOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTCLASSOF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#isContextClassOf"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#isContextInformationParameterOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTINFORMATIONPARAMETEROF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTINFORMATIONPARAMETEROF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#isContextInformationParameterOf"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasAuthor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASAUTHOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASAUTHOR = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasAuthor"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasContentType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCONTENTTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCONTENTTYPE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasContentType"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasDifficulty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDIFFICULTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDIFFICULTY = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasDifficulty"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasIdentifier
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASIDENTIFIER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASIDENTIFIER = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasIdentifier"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasInteractivity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASINTERACTIVITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASINTERACTIVITY = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasInteractivity"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasKeyword
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASKEYWORD.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASKEYWORD = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasKeyword"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasLID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLID = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasLID"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasLanguage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLANGUAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLANGUAGE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasLanguage"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasSubject
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSUBJECT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSUBJECT = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasSubject"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasTrigger
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASTRIGGER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASTRIGGER = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasTrigger"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasVersionDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVERSIONDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVERSIONDATE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasVersionDate"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/motivate.owl#hasConstraintHeadLogicalOperator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCONSTRAINTHEADLOGICALOPERATOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCONSTRAINTHEADLOGICALOPERATOR = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#hasConstraintHeadLogicalOperator"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/motivate.owl#hasContextInformationParameterValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCONTEXTINFORMATIONPARAMETERVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCONTEXTINFORMATIONPARAMETERVALUE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#hasContextInformationParameterValue"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/motivate.owl#hasLearningUnitLogicalOperator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLEARNINGUNITLOGICALOPERATOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLEARNINGUNITLOGICALOPERATOR = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#hasLearningUnitLogicalOperator"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/motivate.owl#hasLogicalOperator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLOGICALOPERATOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLOGICALOPERATOR = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#hasLogicalOperator"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/motivate.owl#hasMeasurableContextInformationValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASMEASURABLECONTEXTINFORMATIONVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASMEASURABLECONTEXTINFORMATIONVALUE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#hasMeasurableContextInformationValue"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/motivate.owl#hasValueOperator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUEOPERATOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUEOPERATOR = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/motivate.owl#hasValueOperator"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasAcquisitionDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASACQUISITIONDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASACQUISITIONDATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasAcquisitionDate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasDataType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDATATYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDATATYPE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasDataType"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasDescription
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasDescription"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasEndTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASENDTIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASENDTIME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasEndTime"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasStartingTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSTARTINGTIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSTARTINGTIME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasStartingTime"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#hasValue"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#isRequired
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISREQUIRED.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISREQUIRED = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/moebert/ontologies/2014/4/untitled-ontology-35#isRequired"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
