package de.unipotsdam.rulegenerator.ontology;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Fri Aug 15 16:43:34 CEST 2014 by tobias
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#AppointmentDetailContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class APPOINTMENTDETAILCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_APPOINTMENTDETAILCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#AppointmentDetailContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#AudioOutputAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AUDIOOUTPUTAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_AUDIOOUTPUTAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#AudioOutputAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#Constraint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONSTRAINT.<p>
     * 
     */
    public static final OWLClass CLASS_CONSTRAINT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#Constraint"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#ConstraintRequirement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_CONSTRAINTREQUIREMENT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#ConstraintRequirement"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#ContentTypeMetaData
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTENTTYPEMETADATA.<p>
     * 
     */
    public static final OWLClass CLASS_CONTENTTYPEMETADATA = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#ContentTypeMetaData"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#ContextClass
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTCLASS.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTCLASS = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#ContextClass"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#ContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#ContextInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#ContextInformationConstraintRequirement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTINFORMATIONCONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTINFORMATIONCONSTRAINTREQUIREMENT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#ContextInformationConstraintRequirement"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#ContextInformationParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTINFORMATIONPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTINFORMATIONPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#ContextInformationParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#CurrentAirPressureMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTAIRPRESSUREMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTAIRPRESSUREMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#CurrentAirPressureMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#CurrentAmbientNoiseMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTAMBIENTNOISEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTAMBIENTNOISEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#CurrentAmbientNoiseMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#CurrentAppointmentMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTAPPOINTMENTMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTAPPOINTMENTMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#CurrentAppointmentMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#CurrentHumidityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTHUMIDITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTHUMIDITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#CurrentHumidityMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#CurrentLearningUnitMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLEARNINGUNITMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLEARNINGUNITMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#CurrentLearningUnitMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#CurrentLuminosityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLUMINOSITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLUMINOSITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#CurrentLuminosityMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#CurrentTemperatureMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTTEMPERATUREMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTTEMPERATUREMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#CurrentTemperatureMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#CurrentTimeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTTIMEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTTIMEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#CurrentTimeMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#CurrentlyRainingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLYRAININGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLYRAININGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#CurrentlyRainingMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#CurrentlySunnyMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLYSUNNYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLYSUNNYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#CurrentlySunnyMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#DateFormatContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATEFORMATCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_DATEFORMATCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#DateFormatContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#DeviceTypeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEVICETYPEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_DEVICETYPEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#DeviceTypeMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#DifficultyMetaData
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DIFFICULTYMETADATA.<p>
     * 
     */
    public static final OWLClass CLASS_DIFFICULTYMETADATA = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#DifficultyMetaData"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#DisplayHorizontalResolutionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISPLAYHORIZONTALRESOLUTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_DISPLAYHORIZONTALRESOLUTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#DisplayHorizontalResolutionMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#DisplayVerticalResolutionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISPLAYVERTICALRESOLUTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_DISPLAYVERTICALRESOLUTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#DisplayVerticalResolutionMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#DistanceUnitContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISTANCEUNITCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_DISTANCEUNITCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#DistanceUnitContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#ExpectedTimeNeededForCompletionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXPECTEDTIMENEEDEDFORCOMPLETIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_EXPECTEDTIMENEEDEDFORCOMPLETIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#ExpectedTimeNeededForCompletionMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#ExternalDisplayAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXTERNALDISPLAYAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_EXTERNALDISPLAYAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#ExternalDisplayAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#Feature
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FEATURE.<p>
     * 
     */
    public static final OWLClass CLASS_FEATURE = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#Feature"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#FeatureConstraint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FEATURECONSTRAINT.<p>
     * 
     */
    public static final OWLClass CLASS_FEATURECONSTRAINT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#FeatureConstraint"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#FinishedLearningUnitMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FINISHEDLEARNINGUNITMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_FINISHEDLEARNINGUNITMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#FinishedLearningUnitMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#HasScreenReaderFunctionalityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HASSCREENREADERFUNCTIONALITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_HASSCREENREADERFUNCTIONALITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#HasScreenReaderFunctionalityMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#IntervalConstraintRequirement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INTERVALCONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_INTERVALCONSTRAINTREQUIREMENT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#IntervalConstraintRequirement"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#LatitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LATITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LATITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#LatitudeContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#LearningUnit
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNIT.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNIT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#LearningUnit"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#LearningUnitConstraint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNITCONSTRAINT.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNITCONSTRAINT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#LearningUnitConstraint"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#LearningUnitIDContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNITIDCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNITIDCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#LearningUnitIDContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#LocationContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOCATIONCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_LOCATIONCONTEXT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#LocationContext"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#LocationContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOCATIONCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_LOCATIONCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#LocationContextInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#LongitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LONGITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LONGITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#LongitudeContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#MeasurableContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEASURABLECONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_MEASURABLECONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#MeasurableContextInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#MetaData
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METADATA.<p>
     * 
     */
    public static final OWLClass CLASS_METADATA = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#MetaData"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#MetaDataConstraintRequirement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METADATACONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_METADATACONSTRAINTREQUIREMENT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#MetaDataConstraintRequirement"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#MicrophoneAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MICROPHONEAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_MICROPHONEAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#MicrophoneAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#MixedContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MIXEDCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_MIXEDCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#MixedContextInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#NavigationTypeMetaData
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NAVIGATIONTYPEMETADATA.<p>
     * 
     */
    public static final OWLClass CLASS_NAVIGATIONTYPEMETADATA = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#NavigationTypeMetaData"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#NextAppointmentMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NEXTAPPOINTMENTMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_NEXTAPPOINTMENTMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#NextAppointmentMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#ParameterizedContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARAMETERIZEDCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PARAMETERIZEDCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#ParameterizedContextInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#PersonalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSONALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_PERSONALCONTEXT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#PersonalContext"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#PersonalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSONALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PERSONALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#PersonalContextInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#PhotoCameraAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHOTOCAMERAAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PHOTOCAMERAAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#PhotoCameraAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#PhysicalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHYSICALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_PHYSICALCONTEXT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#PhysicalContext"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#PhysicalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHYSICALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PHYSICALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#PhysicalContextInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#PressureUnitContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRESSUREUNITCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_PRESSUREUNITCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#PressureUnitContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#PrinterAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRINTERAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PRINTERAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#PrinterAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#PrintingInkContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRINTINGINKCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_PRINTINGINKCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#PrintingInkContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#RankingConstraintRequirement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RANKINGCONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_RANKINGCONSTRAINTREQUIREMENT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#RankingConstraintRequirement"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#ScenarioContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCENARIOCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_SCENARIOCONTEXT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#ScenarioContext"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#ScenarioContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCENARIOCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_SCENARIOCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#ScenarioContextInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#SituationalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITUATIONALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_SITUATIONALCONTEXT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#SituationalContext"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#SituationalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITUATIONALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_SITUATIONALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#SituationalContextInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#TargetLatitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TARGETLATITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TARGETLATITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#TargetLatitudeContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#TargetLongitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TARGETLONGITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TARGETLONGITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#TargetLongitudeContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#TargetTimestampContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TARGETTIMESTAMPCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TARGETTIMESTAMPCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#TargetTimestampContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#TechnicalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TECHNICALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_TECHNICALCONTEXT = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#TechnicalContext"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#TechnicalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TECHNICALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_TECHNICALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#TechnicalContextInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#TemperatureScaleContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPERATURESCALECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPERATURESCALECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#TemperatureScaleContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#TimeUntilTimestampMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TIMEUNTILTIMESTAMPMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_TIMEUNTILTIMESTAMPMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#TimeUntilTimestampMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserCurrentLearningStyleInputMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEINPUTMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEINPUTMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserCurrentLearningStyleInputMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserCurrentLearningStylePerceptionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEPERCEPTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEPERCEPTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserCurrentLearningStylePerceptionMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserCurrentLearningStyleProcessingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEPROCESSINGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEPROCESSINGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserCurrentLearningStyleProcessingMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserCurrentLearningStyleUnderstandingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEUNDERSTANDINGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEUNDERSTANDINGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserCurrentLearningStyleUnderstandingMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserDestinationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERDESTINATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERDESTINATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserDestinationMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserDidArriveAtLocationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERDIDARRIVEATLOCATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERDIDARRIVEATLOCATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserDidArriveAtLocationMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserDidLeaveLocationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERDIDLEAVELOCATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERDIDLEAVELOCATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserDidLeaveLocationMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserIsAtLocationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERISATLOCATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERISATLOCATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserIsAtLocationMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserLocationAddressMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONADDRESSMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONADDRESSMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserLocationAddressMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserLocationBuildingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONBUILDINGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONBUILDINGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserLocationBuildingMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserLocationCountryMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONCOUNTRYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONCOUNTRYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserLocationCountryMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserLocationDistanceMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONDISTANCEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONDISTANCEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserLocationDistanceMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserLocationLatitudeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONLATITUDEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONLATITUDEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserLocationLatitudeMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserLocationLongitudeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONLONGITUDEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONLONGITUDEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserLocationLongitudeMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserLocationRegionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONREGIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONREGIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserLocationRegionMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserMeansOfTransportationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERMEANSOFTRANSPORTATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERMEANSOFTRANSPORTATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserMeansOfTransportationMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserMovementSpeedMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERMOVEMENTSPEEDMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERMOVEMENTSPEEDMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserMovementSpeedMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserRoleMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERROLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERROLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserRoleMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindAngerMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDANGERMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDANGERMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindAngerMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindBoredomMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDBOREDOMMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDBOREDOMMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindBoredomMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindConcentrationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDCONCENTRATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDCONCENTRATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindConcentrationMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindConfusionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDCONFUSIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDCONFUSIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindConfusionMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindCuriosityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDCURIOSITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDCURIOSITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindCuriosityMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindDistractionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDDISTRACTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDDISTRACTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindDistractionMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindHappinessMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDHAPPINESSMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDHAPPINESSMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindHappinessMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindOptimismMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDOPTIMISMMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDOPTIMISMMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindOptimismMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindSadnessMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDSADNESSMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDSADNESSMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindSadnessMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindTirednessMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDTIREDNESSMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDTIREDNESSMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#UserStateOfMindTirednessMeasurableInformation"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#VelocityUnitContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VELOCITYUNITCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_VELOCITYUNITCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#VelocityUnitContextParameter"));

    /* ***************************************************
     * Class http://www.motivate-project.de/ontologies/knowledge#VideoCameraAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VIDEOCAMERAAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_VIDEOCAMERAAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://www.motivate-project.de/ontologies/knowledge#VideoCameraAvailableMeasurableInformation"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasAlternative
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASALTERNATIVE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASALTERNATIVE = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasAlternative"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasBasis
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBASIS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBASIS = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasBasis"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasConstraintMetaData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONSTRAINTMETADATA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONSTRAINTMETADATA = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasConstraintMetaData"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasConstraintRequirement
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONSTRAINTREQUIREMENT = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasConstraintRequirement"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasContextClass
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTCLASS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTCLASS = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasContextClass"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasContextInformation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTINFORMATION = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasContextInformation"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasContextInformationParameter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTINFORMATIONPARAMETER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTINFORMATIONPARAMETER = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasContextInformationParameter"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasContextRequirementMeasurableContextInformation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTREQUIREMENTMEASURABLECONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTREQUIREMENTMEASURABLECONTEXTINFORMATION = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasContextRequirementMeasurableContextInformation"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasExtension
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASEXTENSION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASEXTENSION = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasExtension"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasFeature
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASFEATURE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASFEATURE = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasFeature"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasHelp
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASHELP.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASHELP = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasHelp"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasLearningUnitMeasurableContextInformation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLEARNINGUNITMEASURABLECONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLEARNINGUNITMEASURABLECONTEXTINFORMATION = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasLearningUnitMeasurableContextInformation"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasLearningUnitMetaData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLEARNINGUNITMETADATA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLEARNINGUNITMETADATA = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasLearningUnitMetaData"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasMeasurableContextInformation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMEASURABLECONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMEASURABLECONTEXTINFORMATION = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasMeasurableContextInformation"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasMetaData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMETADATA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMETADATA = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasMetaData"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasPrerequisite
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPREREQUISITE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPREREQUISITE = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasPrerequisite"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasReference
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASREFERENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASREFERENCE = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasReference"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasRelation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRELATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRELATION = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasRelation"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasVersion
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASVERSION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASVERSION = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasVersion"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isBasisOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISBASISOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISBASISOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isBasisOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isConstraintTailOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONSTRAINTTAILOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONSTRAINTTAILOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isConstraintTailOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isContextClassOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTCLASSOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTCLASSOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isContextClassOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isContextInformationOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTINFORMATIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTINFORMATIONOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isContextInformationOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isContextInformationParameterOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTINFORMATIONPARAMETEROF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTINFORMATIONPARAMETEROF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isContextInformationParameterOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isExtensionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISEXTENSIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISEXTENSIONOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isExtensionOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isHelpOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISHELPOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISHELPOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isHelpOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isMeasurableContextInformationOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISMEASURABLECONTEXTINFORMATIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISMEASURABLECONTEXTINFORMATIONOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isMeasurableContextInformationOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isPrerequisiteOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPREREQUISITEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPREREQUISITEOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isPrerequisiteOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isReferenceOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISREFERENCEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISREFERENCEOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isReferenceOf"));

    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#isVersionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISVERSIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISVERSIONOF = factory.getOWLObjectProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isVersionOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL_TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasAcquisitionDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASACQUISITIONDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASACQUISITIONDATE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasAcquisitionDate"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasAuthor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASAUTHOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASAUTHOR = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasAuthor"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasConstraintLogicalOperator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCONSTRAINTLOGICALOPERATOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCONSTRAINTLOGICALOPERATOR = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasConstraintLogicalOperator"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasContentType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCONTENTTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCONTENTTYPE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasContentType"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasContextInformationParameterValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCONTEXTINFORMATIONPARAMETERVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCONTEXTINFORMATIONPARAMETERVALUE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasContextInformationParameterValue"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasDataType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDATATYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDATATYPE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasDataType"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasDescription
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasDescription"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasDifficulty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDIFFICULTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDIFFICULTY = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasDifficulty"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasEndTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASENDTIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASENDTIME = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasEndTime"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasIdentifier
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASIDENTIFIER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASIDENTIFIER = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasIdentifier"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasImageContentMetaData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASIMAGECONTENTMETADATA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASIMAGECONTENTMETADATA = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasImageContentMetaData"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasInteractivity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASINTERACTIVITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASINTERACTIVITY = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasInteractivity"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasKeyword
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASKEYWORD.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASKEYWORD = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasKeyword"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasLID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLID = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasLID"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasLanguage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLANGUAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLANGUAGE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasLanguage"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasLearningUnitLogicalOperator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLEARNINGUNITLOGICALOPERATOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLEARNINGUNITLOGICALOPERATOR = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasLearningUnitLogicalOperator"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasLogicalOperator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLOGICALOPERATOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLOGICALOPERATOR = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasLogicalOperator"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasMeasurableContextInformationValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASMEASURABLECONTEXTINFORMATIONVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASMEASURABLECONTEXTINFORMATIONVALUE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasMeasurableContextInformationValue"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasMetaData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASMETADATA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASMETADATA = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasMetaData"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAME = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasName"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasStartingTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSTARTINGTIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSTARTINGTIME = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasStartingTime"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasSubject
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSUBJECT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSUBJECT = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasSubject"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasTextualContentMetaData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASTEXTUALCONTENTMETADATA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASTEXTUALCONTENTMETADATA = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasTextualContentMetaData"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasTrigger
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASTRIGGER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASTRIGGER = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasTrigger"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasValue"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasValueOperator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUEOPERATOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUEOPERATOR = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasValueOperator"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasVersionDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVERSIONDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVERSIONDATE = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasVersionDate"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasVideoContentMetaData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVIDEOCONTENTMETADATA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVIDEOCONTENTMETADATA = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#hasVideoContentMetaData"));

    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#isRequired
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISREQUIRED.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISREQUIRED = factory.getOWLDataProperty(IRI.create("http://www.motivate-project.de/ontologies/knowledge#isRequired"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OWL_TOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
