package de.unipotsdam.rulegenerator.ontology.impl;

import de.unipotsdam.rulegenerator.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultRestrictRelationsConstraintHead <br>
 * @version generated on Wed Aug 13 14:30:39 CEST 2014 by tobias
 */
public class DefaultRestrictRelationsConstraintHead extends WrappedIndividualImpl implements RestrictRelationsConstraintHead {

    public DefaultRestrictRelationsConstraintHead(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasConstraintTail
     */
     
    public Collection<? extends WrappedIndividual> getHasConstraintTail() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASCONSTRAINTTAIL,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasConstraintTail() {
	   return !getHasConstraintTail().isEmpty();
    }

    public void addHasConstraintTail(WrappedIndividual newHasConstraintTail) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASCONSTRAINTTAIL,
                                       newHasConstraintTail);
    }

    public void removeHasConstraintTail(WrappedIndividual oldHasConstraintTail) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASCONSTRAINTTAIL,
                                          oldHasConstraintTail);
    }


    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasConstraintHeadLogicalOperator
     */
     
    public Collection<? extends Object> getHasConstraintHeadLogicalOperator() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONSTRAINTHEADLOGICALOPERATOR, Object.class);
    }

    public boolean hasHasConstraintHeadLogicalOperator() {
		return !getHasConstraintHeadLogicalOperator().isEmpty();
    }

    public void addHasConstraintHeadLogicalOperator(Object newHasConstraintHeadLogicalOperator) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONSTRAINTHEADLOGICALOPERATOR, newHasConstraintHeadLogicalOperator);
    }

    public void removeHasConstraintHeadLogicalOperator(Object oldHasConstraintHeadLogicalOperator) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONSTRAINTHEADLOGICALOPERATOR, oldHasConstraintHeadLogicalOperator);
    }


}
