package de.unipotsdam.rulegenerator.ontology.impl;

import de.unipotsdam.rulegenerator.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultPhysicalContext <br>
 * @version generated on Wed Jul 16 14:45:16 CEST 2014 by tobias
 */
public class DefaultPhysicalContext extends WrappedIndividualImpl implements PhysicalContext {

    public DefaultPhysicalContext(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
