package de.unipotsdam.rulegenerator.ontology.impl;

import de.unipotsdam.rulegenerator.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultIntervalConstraintTail <br>
 * @version generated on Wed Aug 13 14:30:39 CEST 2014 by tobias
 */
public class DefaultIntervalConstraintTail extends WrappedIndividualImpl implements IntervalConstraintTail {

    public DefaultIntervalConstraintTail(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.motivate-project.de/ontologies/knowledge#hasContextTailMeasurableContextInformation
     */
     
    public Collection<? extends MeasurableContextInformation> getHasContextTailMeasurableContextInformation() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASCONTEXTTAILMEASURABLECONTEXTINFORMATION,
                                               DefaultMeasurableContextInformation.class);
    }

    public boolean hasHasContextTailMeasurableContextInformation() {
	   return !getHasContextTailMeasurableContextInformation().isEmpty();
    }

    public void addHasContextTailMeasurableContextInformation(MeasurableContextInformation newHasContextTailMeasurableContextInformation) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASCONTEXTTAILMEASURABLECONTEXTINFORMATION,
                                       newHasContextTailMeasurableContextInformation);
    }

    public void removeHasContextTailMeasurableContextInformation(MeasurableContextInformation oldHasContextTailMeasurableContextInformation) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASCONTEXTTAILMEASURABLECONTEXTINFORMATION,
                                          oldHasContextTailMeasurableContextInformation);
    }


}
