package de.unipotsdam.rulegenerator.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: PauseAction <br>
 * @version generated on Mon Feb 09 12:46:06 CET 2015 by tobias
 */

public interface PauseAction extends Action {

    /* ***************************************************
     * Property http://motivate-project.de/ontology/knowledge.owl#hasAID
     */
     
    /**
     * Gets all property values for the hasAID property.<p>
     * 
     * @returns a collection of values for the hasAID property.
     */
    Collection<? extends String> getHasAID();

    /**
     * Checks if the class has a hasAID property value.<p>
     * 
     * @return true if there is a hasAID property value.
     */
    boolean hasHasAID();

    /**
     * Adds a hasAID property value.<p>
     * 
     * @param newHasAID the hasAID property value to be added
     */
    void addHasAID(String newHasAID);

    /**
     * Removes a hasAID property value.<p>
     * 
     * @param oldHasAID the hasAID property value to be removed.
     */
    void removeHasAID(String oldHasAID);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
