package de.unipotsdam.rulegenerator.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: User <br>
 * @version generated on Wed Oct 07 15:25:17 CEST 2015 by tobias
 */

public interface User extends WrappedIndividual {

    /* ***************************************************
     * Property http://motivate-project.de/ontology/knowledge.owl#hasUID
     */
     
    /**
     * Gets all property values for the hasUID property.<p>
     * 
     * @returns a collection of values for the hasUID property.
     */
    Collection<? extends String> getHasUID();

    /**
     * Checks if the class has a hasUID property value.<p>
     * 
     * @return true if there is a hasUID property value.
     */
    boolean hasHasUID();

    /**
     * Adds a hasUID property value.<p>
     * 
     * @param newHasUID the hasUID property value to be added
     */
    void addHasUID(String newHasUID);

    /**
     * Removes a hasUID property value.<p>
     * 
     * @param oldHasUID the hasUID property value to be removed.
     */
    void removeHasUID(String oldHasUID);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
