package de.unipotsdam.rulegenerator.ontology;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Thu Dec 04 13:00:54 CET 2014 by tobias
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#Action
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACTION.<p>
     * 
     */
    public static final OWLClass CLASS_ACTION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#Action"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#AppointmentDetailContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class APPOINTMENTDETAILCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_APPOINTMENTDETAILCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#AppointmentDetailContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#AudioOutputAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AUDIOOUTPUTAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_AUDIOOUTPUTAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#AudioOutputAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#CancelAction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CANCELACTION.<p>
     * 
     */
    public static final OWLClass CLASS_CANCELACTION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#CancelAction"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#Constraint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONSTRAINT.<p>
     * 
     */
    public static final OWLClass CLASS_CONSTRAINT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#Constraint"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#ConstraintRequirement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_CONSTRAINTREQUIREMENT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#ConstraintRequirement"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#ContextClass
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTCLASS.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTCLASS = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#ContextClass"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#ContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#ContextInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#ContextInformationConstraintRequirement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTINFORMATIONCONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTINFORMATIONCONSTRAINTREQUIREMENT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#ContextInformationConstraintRequirement"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#ContextInformationParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTINFORMATIONPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTINFORMATIONPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#ContextInformationParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#CurrentAirPressureMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTAIRPRESSUREMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTAIRPRESSUREMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#CurrentAirPressureMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#CurrentAmbientNoiseMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTAMBIENTNOISEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTAMBIENTNOISEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#CurrentAmbientNoiseMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#CurrentAppointmentMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTAPPOINTMENTMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTAPPOINTMENTMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#CurrentAppointmentMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#CurrentHumidityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTHUMIDITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTHUMIDITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#CurrentHumidityMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#CurrentLearningUnitMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLEARNINGUNITMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLEARNINGUNITMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#CurrentLearningUnitMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#CurrentLuminosityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLUMINOSITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLUMINOSITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#CurrentLuminosityMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#CurrentTemperatureMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTTEMPERATUREMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTTEMPERATUREMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#CurrentTemperatureMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#CurrentTimeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTTIMEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTTIMEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#CurrentTimeMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#CurrentlyRainingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLYRAININGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLYRAININGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#CurrentlyRainingMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#CurrentlySunnyMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLYSUNNYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLYSUNNYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#CurrentlySunnyMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#DateFormatContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATEFORMATCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_DATEFORMATCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#DateFormatContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#DeviceTypeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEVICETYPEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_DEVICETYPEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#DeviceTypeMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#DisplayHorizontalResolutionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISPLAYHORIZONTALRESOLUTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_DISPLAYHORIZONTALRESOLUTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#DisplayHorizontalResolutionMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#DisplayVerticalResolutionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISPLAYVERTICALRESOLUTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_DISPLAYVERTICALRESOLUTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#DisplayVerticalResolutionMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#DistanceUnitContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISTANCEUNITCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_DISTANCEUNITCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#DistanceUnitContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#ExpectedTimeNeededForCompletionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXPECTEDTIMENEEDEDFORCOMPLETIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_EXPECTEDTIMENEEDEDFORCOMPLETIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#ExpectedTimeNeededForCompletionMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#ExternalDisplayAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXTERNALDISPLAYAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_EXTERNALDISPLAYAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#ExternalDisplayAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#Feature
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FEATURE.<p>
     * 
     */
    public static final OWLClass CLASS_FEATURE = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#Feature"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#FinishAction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FINISHACTION.<p>
     * 
     */
    public static final OWLClass CLASS_FINISHACTION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#FinishAction"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#FinishedLearningUnitMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FINISHEDLEARNINGUNITMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_FINISHEDLEARNINGUNITMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#FinishedLearningUnitMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#HasScreenReaderFunctionalityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HASSCREENREADERFUNCTIONALITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_HASSCREENREADERFUNCTIONALITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#HasScreenReaderFunctionalityMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#LatitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LATITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LATITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#LatitudeContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#LearningUnit
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNIT.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNIT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#LearningUnit"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#LearningUnitClass
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNITCLASS.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNITCLASS = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#LearningUnitClass"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#LearningUnitClassConstraint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNITCLASSCONSTRAINT.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNITCLASSCONSTRAINT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#LearningUnitClassConstraint"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#LearningUnitIDContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNITIDCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNITIDCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#LearningUnitIDContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#LocationContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOCATIONCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_LOCATIONCONTEXT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#LocationContext"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#LocationContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOCATIONCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_LOCATIONCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#LocationContextInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#LongitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LONGITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LONGITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#LongitudeContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#MeasurableContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEASURABLECONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_MEASURABLECONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#MeasurableContextInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#MicrophoneAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MICROPHONEAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_MICROPHONEAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#MicrophoneAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#MixedContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MIXEDCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_MIXEDCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#MixedContextInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#NextAppointmentMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NEXTAPPOINTMENTMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_NEXTAPPOINTMENTMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#NextAppointmentMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#ParameterizedContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARAMETERIZEDCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PARAMETERIZEDCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#ParameterizedContextInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#PauseAction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PAUSEACTION.<p>
     * 
     */
    public static final OWLClass CLASS_PAUSEACTION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#PauseAction"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#PersonalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSONALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_PERSONALCONTEXT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#PersonalContext"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#PersonalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSONALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PERSONALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#PersonalContextInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#PhotoCameraAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHOTOCAMERAAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PHOTOCAMERAAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#PhotoCameraAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#PhysicalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHYSICALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_PHYSICALCONTEXT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#PhysicalContext"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#PhysicalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHYSICALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PHYSICALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#PhysicalContextInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#PressureUnitContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRESSUREUNITCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_PRESSUREUNITCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#PressureUnitContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#PrinterAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRINTERAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PRINTERAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#PrinterAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#PrintingInkContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRINTINGINKCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_PRINTINGINKCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#PrintingInkContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#RankingConstraintRequirement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RANKINGCONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_RANKINGCONSTRAINTREQUIREMENT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#RankingConstraintRequirement"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#Reason
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REASON.<p>
     * 
     */
    public static final OWLClass CLASS_REASON = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#Reason"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#RecordedContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RECORDEDCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_RECORDEDCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#RecordedContextInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#RestrictFeatureConstraint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESTRICTFEATURECONSTRAINT.<p>
     * 
     */
    public static final OWLClass CLASS_RESTRICTFEATURECONSTRAINT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#RestrictFeatureConstraint"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#ScenarioContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCENARIOCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_SCENARIOCONTEXT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#ScenarioContext"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#ScenarioContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCENARIOCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_SCENARIOCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#ScenarioContextInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#Situation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITUATION.<p>
     * 
     */
    public static final OWLClass CLASS_SITUATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#Situation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#SituationalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITUATIONALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_SITUATIONALCONTEXT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#SituationalContext"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#SituationalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITUATIONALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_SITUATIONALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#SituationalContextInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#StartAction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STARTACTION.<p>
     * 
     */
    public static final OWLClass CLASS_STARTACTION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#StartAction"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#TargetLatitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TARGETLATITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TARGETLATITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#TargetLatitudeContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#TargetLongitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TARGETLONGITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TARGETLONGITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#TargetLongitudeContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#TargetTimestampContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TARGETTIMESTAMPCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TARGETTIMESTAMPCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#TargetTimestampContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#TechnicalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TECHNICALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_TECHNICALCONTEXT = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#TechnicalContext"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#TechnicalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TECHNICALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_TECHNICALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#TechnicalContextInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#TemperatureScaleContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPERATURESCALECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPERATURESCALECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#TemperatureScaleContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#TimeUntilTimestampMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TIMEUNTILTIMESTAMPMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_TIMEUNTILTIMESTAMPMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#TimeUntilTimestampMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#TransmissionAction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TRANSMISSIONACTION.<p>
     * 
     */
    public static final OWLClass CLASS_TRANSMISSIONACTION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#TransmissionAction"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#User
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USER.<p>
     * 
     */
    public static final OWLClass CLASS_USER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#User"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserAgeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERAGEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERAGEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserAgeMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserCurrentLearningStyleInputMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEINPUTMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEINPUTMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserCurrentLearningStyleInputMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserCurrentLearningStylePerceptionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEPERCEPTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEPERCEPTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserCurrentLearningStylePerceptionMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserCurrentLearningStyleProcessingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEPROCESSINGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEPROCESSINGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserCurrentLearningStyleProcessingMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserCurrentLearningStyleUnderstandingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEUNDERSTANDINGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEUNDERSTANDINGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserCurrentLearningStyleUnderstandingMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserDestinationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERDESTINATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERDESTINATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserDestinationMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserDidArriveAtLocationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERDIDARRIVEATLOCATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERDIDARRIVEATLOCATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserDidArriveAtLocationMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserDidLeaveLocationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERDIDLEAVELOCATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERDIDLEAVELOCATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserDidLeaveLocationMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserIsAtLocationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERISATLOCATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERISATLOCATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserIsAtLocationMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserLocationAddressMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONADDRESSMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONADDRESSMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserLocationAddressMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserLocationBuildingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONBUILDINGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONBUILDINGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserLocationBuildingMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserLocationCountryMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONCOUNTRYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONCOUNTRYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserLocationCountryMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserLocationDistanceMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONDISTANCEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONDISTANCEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserLocationDistanceMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserLocationLatitudeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONLATITUDEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONLATITUDEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserLocationLatitudeMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserLocationLongitudeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONLONGITUDEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONLONGITUDEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserLocationLongitudeMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserLocationRegionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONREGIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONREGIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserLocationRegionMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserMeansOfTransportationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERMEANSOFTRANSPORTATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERMEANSOFTRANSPORTATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserMeansOfTransportationMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserMovementSpeedMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERMOVEMENTSPEEDMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERMOVEMENTSPEEDMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserMovementSpeedMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserRoleMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERROLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERROLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserRoleMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindAngerMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDANGERMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDANGERMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindAngerMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindBoredomMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDBOREDOMMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDBOREDOMMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindBoredomMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindConcentrationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDCONCENTRATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDCONCENTRATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindConcentrationMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindConfusionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDCONFUSIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDCONFUSIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindConfusionMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindCuriosityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDCURIOSITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDCURIOSITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindCuriosityMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindDistractionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDDISTRACTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDDISTRACTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindDistractionMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindHappinessMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDHAPPINESSMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDHAPPINESSMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindHappinessMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindOptimismMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDOPTIMISMMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDOPTIMISMMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindOptimismMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindSadnessMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDSADNESSMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDSADNESSMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindSadnessMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindTirednessMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDTIREDNESSMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDTIREDNESSMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#UserStateOfMindTirednessMeasurableInformation"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#VelocityUnitContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VELOCITYUNITCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_VELOCITYUNITCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#VelocityUnitContextParameter"));

    /* ***************************************************
     * Class http://motivate-project.de/ontology/knowledge.owl#VideoCameraAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VIDEOCAMERAAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_VIDEOCAMERAAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://motivate-project.de/ontology/knowledge.owl#VideoCameraAvailableMeasurableInformation"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasAction
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASACTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASACTION = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasAction"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasAlternative
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASALTERNATIVE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASALTERNATIVE = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasAlternative"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasBasis
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBASIS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBASIS = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasBasis"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasConstraintRequirement
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONSTRAINTREQUIREMENT = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasConstraintRequirement"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasContextClass
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTCLASS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTCLASS = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasContextClass"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasContextInformation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTINFORMATION = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasContextInformation"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasContextInformationParameter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTINFORMATIONPARAMETER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTINFORMATIONPARAMETER = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasContextInformationParameter"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasExtension
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASEXTENSION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASEXTENSION = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasExtension"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasFeature
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASFEATURE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASFEATURE = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasFeature"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasHelp
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASHELP.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASHELP = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasHelp"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasLearningUnit
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLEARNINGUNIT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLEARNINGUNIT = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasLearningUnit"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasLearningUnitClass
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLEARNINGUNITCLASS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLEARNINGUNITCLASS = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasLearningUnitClass"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasMeasurableContextInformation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMEASURABLECONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMEASURABLECONTEXTINFORMATION = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasMeasurableContextInformation"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasNotLearningUnitClass
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASNOTLEARNINGUNITCLASS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASNOTLEARNINGUNITCLASS = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasNotLearningUnitClass"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasPrerequisite
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPREREQUISITE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPREREQUISITE = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasPrerequisite"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasReason
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASREASON.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASREASON = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasReason"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasRecordedContextInformation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRECORDEDCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRECORDEDCONTEXTINFORMATION = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasRecordedContextInformation"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasReference
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASREFERENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASREFERENCE = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasReference"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasRelation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRELATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRELATION = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasRelation"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasSituation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSITUATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSITUATION = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasSituation"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#hasVersion
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASVERSION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASVERSION = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasVersion"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isActionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISACTIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISACTIONOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isActionOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isBasisOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISBASISOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISBASISOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isBasisOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isConstraintRequirementOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONSTRAINTREQUIREMENTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONSTRAINTREQUIREMENTOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isConstraintRequirementOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isContextClassOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTCLASSOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTCLASSOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isContextClassOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isContextInformationOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTINFORMATIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTINFORMATIONOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isContextInformationOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isContextInformationParameterOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTINFORMATIONPARAMETEROF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTINFORMATIONPARAMETEROF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isContextInformationParameterOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isExtensionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISEXTENSIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISEXTENSIONOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isExtensionOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isFeatureOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISFEATUREOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISFEATUREOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isFeatureOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isHelpOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISHELPOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISHELPOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isHelpOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isLearningUnitClassOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISLEARNINGUNITCLASSOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISLEARNINGUNITCLASSOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isLearningUnitClassOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isMeasurableContextInformationOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISMEASURABLECONTEXTINFORMATIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISMEASURABLECONTEXTINFORMATIONOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isMeasurableContextInformationOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isPrerequisiteOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPREREQUISITEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPREREQUISITEOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isPrerequisiteOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isRecordedContextInformationOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISRECORDEDCONTEXTINFORMATIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISRECORDEDCONTEXTINFORMATIONOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isRecordedContextInformationOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isReferenceOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISREFERENCEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISREFERENCEOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isReferenceOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isReferencedByAction
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISREFERENCEDBYACTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISREFERENCEDBYACTION = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isReferencedByAction"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isReferencedByCancelAction
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISREFERENCEDBYCANCELACTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISREFERENCEDBYCANCELACTION = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isReferencedByCancelAction"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isReferencedByStartAction
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISREFERENCEDBYSTARTACTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISREFERENCEDBYSTARTACTION = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isReferencedByStartAction"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isSituationOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSITUATIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSITUATIONOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isSituationOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#isVersionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISVERSIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISVERSIONOF = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isVersionOf"));

    /* ***************************************************
     * Object Property http://motivate-project.de/ontology/knowledge.owl#referencesLearningUnit
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REFERENCESLEARNINGUNIT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REFERENCESLEARNINGUNIT = factory.getOWLObjectProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#referencesLearningUnit"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasAID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASAID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASAID = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasAID"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasAcquisitionDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASACQUISITIONDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASACQUISITIONDATE = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasAcquisitionDate"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasAgeLimit
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASAGELIMIT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASAGELIMIT = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasAgeLimit"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasAuthor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASAUTHOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASAUTHOR = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasAuthor"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasContentType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCONTENTTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCONTENTTYPE = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasContentType"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasDataType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDATATYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDATATYPE = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasDataType"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasDescription
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDESCRIPTION = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasDescription"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasDifficulty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDIFFICULTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDIFFICULTY = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasDifficulty"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasEndTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASENDTIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASENDTIME = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasEndTime"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasIdentifier
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASIDENTIFIER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASIDENTIFIER = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasIdentifier"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasInteractivity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASINTERACTIVITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASINTERACTIVITY = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasInteractivity"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasKeyword
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASKEYWORD.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASKEYWORD = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasKeyword"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasLID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLID = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasLID"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasLanguage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLANGUAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLANGUAGE = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasLanguage"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasLogicalOperator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLOGICALOPERATOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLOGICALOPERATOR = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasLogicalOperator"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasMetaData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASMETADATA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASMETADATA = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasMetaData"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAME = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasName"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasNavigationType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAVIGATIONTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAVIGATIONTYPE = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasNavigationType"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasStartingTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSTARTINGTIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSTARTINGTIME = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasStartingTime"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasSubject
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSUBJECT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSUBJECT = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasSubject"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASTIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASTIME = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasTime"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasTimestamp
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASTIMESTAMP.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASTIMESTAMP = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasTimestamp"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasTrigger
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASTRIGGER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASTRIGGER = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasTrigger"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasUID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASUID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASUID = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasUID"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasUserCorrectedValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASUSERCORRECTEDVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASUSERCORRECTEDVALUE = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasUserCorrectedValue"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUE = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasValue"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasValueOperator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUEOPERATOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUEOPERATOR = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasValueOperator"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#hasVersionDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVERSIONDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVERSIONDATE = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#hasVersionDate"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#isFalsePositive
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISFALSEPOSITIVE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISFALSEPOSITIVE = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isFalsePositive"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#isRequired
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISREQUIRED.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISREQUIRED = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isRequired"));

    /* ***************************************************
     * Data Property http://motivate-project.de/ontology/knowledge.owl#isScreenReaderSuitable
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISSCREENREADERSUITABLE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISSCREENREADERSUITABLE = factory.getOWLDataProperty(IRI.create("http://motivate-project.de/ontology/knowledge.owl#isScreenReaderSuitable"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
