package de.unipotsdam.rulegenerator.ontology;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Tue Sep 02 15:45:18 CEST 2014 by tobias
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#AgeLimitMetaData
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AGELIMITMETADATA.<p>
     * 
     */
    public static final OWLClass CLASS_AGELIMITMETADATA = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#AgeLimitMetaData"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#AppointmentDetailContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class APPOINTMENTDETAILCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_APPOINTMENTDETAILCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#AppointmentDetailContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#AudioOutputAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AUDIOOUTPUTAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_AUDIOOUTPUTAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#AudioOutputAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#Constraint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONSTRAINT.<p>
     * 
     */
    public static final OWLClass CLASS_CONSTRAINT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#Constraint"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#ConstraintRequirement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_CONSTRAINTREQUIREMENT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#ConstraintRequirement"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#ContentTypeMetaData
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTENTTYPEMETADATA.<p>
     * 
     */
    public static final OWLClass CLASS_CONTENTTYPEMETADATA = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#ContentTypeMetaData"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#ContextClass
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTCLASS.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTCLASS = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#ContextClass"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#ContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#ContextInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#ContextInformationConstraintRequirement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTINFORMATIONCONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTINFORMATIONCONSTRAINTREQUIREMENT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#ContextInformationConstraintRequirement"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#ContextInformationParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXTINFORMATIONPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXTINFORMATIONPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#ContextInformationParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#CurrentAirPressureMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTAIRPRESSUREMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTAIRPRESSUREMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#CurrentAirPressureMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#CurrentAmbientNoiseMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTAMBIENTNOISEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTAMBIENTNOISEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#CurrentAmbientNoiseMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#CurrentAppointmentMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTAPPOINTMENTMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTAPPOINTMENTMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#CurrentAppointmentMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#CurrentHumidityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTHUMIDITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTHUMIDITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#CurrentHumidityMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#CurrentLearningUnitMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLEARNINGUNITMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLEARNINGUNITMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#CurrentLearningUnitMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#CurrentLuminosityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLUMINOSITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLUMINOSITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#CurrentLuminosityMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#CurrentTemperatureMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTTEMPERATUREMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTTEMPERATUREMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#CurrentTemperatureMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#CurrentTimeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTTIMEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTTIMEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#CurrentTimeMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#CurrentlyRainingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLYRAININGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLYRAININGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#CurrentlyRainingMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#CurrentlySunnyMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTLYSUNNYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTLYSUNNYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#CurrentlySunnyMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#DateFormatContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATEFORMATCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_DATEFORMATCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#DateFormatContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#DeviceTypeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEVICETYPEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_DEVICETYPEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#DeviceTypeMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#DifficultyMetaData
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DIFFICULTYMETADATA.<p>
     * 
     */
    public static final OWLClass CLASS_DIFFICULTYMETADATA = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#DifficultyMetaData"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#DisplayHorizontalResolutionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISPLAYHORIZONTALRESOLUTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_DISPLAYHORIZONTALRESOLUTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#DisplayHorizontalResolutionMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#DisplayVerticalResolutionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISPLAYVERTICALRESOLUTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_DISPLAYVERTICALRESOLUTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#DisplayVerticalResolutionMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#DistanceUnitContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISTANCEUNITCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_DISTANCEUNITCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#DistanceUnitContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#ExpectedTimeNeededForCompletionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXPECTEDTIMENEEDEDFORCOMPLETIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_EXPECTEDTIMENEEDEDFORCOMPLETIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#ExpectedTimeNeededForCompletionMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#ExternalDisplayAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXTERNALDISPLAYAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_EXTERNALDISPLAYAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#ExternalDisplayAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#Feature
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FEATURE.<p>
     * 
     */
    public static final OWLClass CLASS_FEATURE = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#Feature"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#FinishedLearningUnitMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FINISHEDLEARNINGUNITMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_FINISHEDLEARNINGUNITMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#FinishedLearningUnitMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#HasScreenReaderFunctionalityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HASSCREENREADERFUNCTIONALITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_HASSCREENREADERFUNCTIONALITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#HasScreenReaderFunctionalityMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#LatitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LATITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LATITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#LatitudeContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#LearningUnit
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNIT.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNIT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#LearningUnit"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#LearningUnitClass
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNITCLASS.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNITCLASS = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#LearningUnitClass"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#LearningUnitClassConstraint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNITCLASSCONSTRAINT.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNITCLASSCONSTRAINT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#LearningUnitClassConstraint"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#LearningUnitIDContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEARNINGUNITIDCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LEARNINGUNITIDCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#LearningUnitIDContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#LocationContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOCATIONCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_LOCATIONCONTEXT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#LocationContext"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#LocationContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOCATIONCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_LOCATIONCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#LocationContextInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#LongitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LONGITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LONGITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#LongitudeContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#MeasurableContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEASURABLECONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_MEASURABLECONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#MeasurableContextInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#MetaData
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METADATA.<p>
     * 
     */
    public static final OWLClass CLASS_METADATA = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#MetaData"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#MicrophoneAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MICROPHONEAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_MICROPHONEAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#MicrophoneAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#MixedContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MIXEDCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_MIXEDCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#MixedContextInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#NavigationTypeMetaData
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NAVIGATIONTYPEMETADATA.<p>
     * 
     */
    public static final OWLClass CLASS_NAVIGATIONTYPEMETADATA = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#NavigationTypeMetaData"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#NextAppointmentMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NEXTAPPOINTMENTMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_NEXTAPPOINTMENTMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#NextAppointmentMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#ParameterizedContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARAMETERIZEDCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PARAMETERIZEDCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#ParameterizedContextInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#PersonalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSONALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_PERSONALCONTEXT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#PersonalContext"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#PersonalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSONALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PERSONALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#PersonalContextInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#PhotoCameraAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHOTOCAMERAAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PHOTOCAMERAAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#PhotoCameraAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#PhysicalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHYSICALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_PHYSICALCONTEXT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#PhysicalContext"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#PhysicalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHYSICALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PHYSICALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#PhysicalContextInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#PressureUnitContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRESSUREUNITCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_PRESSUREUNITCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#PressureUnitContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#PrinterAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRINTERAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PRINTERAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#PrinterAvailableMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#PrintingInkContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRINTINGINKCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_PRINTINGINKCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#PrintingInkContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#RankingConstraintRequirement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RANKINGCONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_RANKINGCONSTRAINTREQUIREMENT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#RankingConstraintRequirement"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#RestrictFeatureConstraint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESTRICTFEATURECONSTRAINT.<p>
     * 
     */
    public static final OWLClass CLASS_RESTRICTFEATURECONSTRAINT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#RestrictFeatureConstraint"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#ScenarioContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCENARIOCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_SCENARIOCONTEXT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#ScenarioContext"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#ScenarioContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCENARIOCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_SCENARIOCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#ScenarioContextInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#ScreenReaderSuitableMetaData
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCREENREADERSUITABLEMETADATA.<p>
     * 
     */
    public static final OWLClass CLASS_SCREENREADERSUITABLEMETADATA = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#ScreenReaderSuitableMetaData"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#SituationalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITUATIONALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_SITUATIONALCONTEXT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#SituationalContext"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#SituationalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITUATIONALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_SITUATIONALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#SituationalContextInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#TargetLatitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TARGETLATITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TARGETLATITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#TargetLatitudeContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#TargetLongitudeContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TARGETLONGITUDECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TARGETLONGITUDECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#TargetLongitudeContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#TargetTimestampContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TARGETTIMESTAMPCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TARGETTIMESTAMPCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#TargetTimestampContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#TechnicalContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TECHNICALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_TECHNICALCONTEXT = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#TechnicalContext"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#TechnicalContextInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TECHNICALCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_TECHNICALCONTEXTINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#TechnicalContextInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#TemperatureScaleContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPERATURESCALECONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPERATURESCALECONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#TemperatureScaleContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#TimeUntilTimestampMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TIMEUNTILTIMESTAMPMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_TIMEUNTILTIMESTAMPMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#TimeUntilTimestampMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserAgeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERAGEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERAGEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserAgeMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserCurrentLearningStyleInputMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEINPUTMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEINPUTMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserCurrentLearningStyleInputMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserCurrentLearningStylePerceptionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEPERCEPTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEPERCEPTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserCurrentLearningStylePerceptionMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserCurrentLearningStyleProcessingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEPROCESSINGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEPROCESSINGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserCurrentLearningStyleProcessingMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserCurrentLearningStyleUnderstandingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERCURRENTLEARNINGSTYLEUNDERSTANDINGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERCURRENTLEARNINGSTYLEUNDERSTANDINGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserCurrentLearningStyleUnderstandingMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserDestinationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERDESTINATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERDESTINATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserDestinationMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserDidArriveAtLocationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERDIDARRIVEATLOCATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERDIDARRIVEATLOCATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserDidArriveAtLocationMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserDidLeaveLocationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERDIDLEAVELOCATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERDIDLEAVELOCATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserDidLeaveLocationMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserIsAtLocationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERISATLOCATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERISATLOCATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserIsAtLocationMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserLocationAddressMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONADDRESSMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONADDRESSMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserLocationAddressMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserLocationBuildingMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONBUILDINGMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONBUILDINGMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserLocationBuildingMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserLocationCountryMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONCOUNTRYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONCOUNTRYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserLocationCountryMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserLocationDistanceMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONDISTANCEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONDISTANCEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserLocationDistanceMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserLocationLatitudeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONLATITUDEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONLATITUDEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserLocationLatitudeMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserLocationLongitudeMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONLONGITUDEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONLONGITUDEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserLocationLongitudeMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserLocationRegionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERLOCATIONREGIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERLOCATIONREGIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserLocationRegionMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserMeansOfTransportationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERMEANSOFTRANSPORTATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERMEANSOFTRANSPORTATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserMeansOfTransportationMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserMovementSpeedMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERMOVEMENTSPEEDMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERMOVEMENTSPEEDMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserMovementSpeedMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserRoleMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERROLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERROLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserRoleMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindAngerMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDANGERMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDANGERMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindAngerMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindBoredomMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDBOREDOMMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDBOREDOMMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindBoredomMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindConcentrationMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDCONCENTRATIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDCONCENTRATIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindConcentrationMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindConfusionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDCONFUSIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDCONFUSIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindConfusionMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindCuriosityMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDCURIOSITYMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDCURIOSITYMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindCuriosityMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindDistractionMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDDISTRACTIONMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDDISTRACTIONMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindDistractionMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindHappinessMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDHAPPINESSMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDHAPPINESSMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindHappinessMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindOptimismMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDOPTIMISMMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDOPTIMISMMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindOptimismMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindSadnessMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDSADNESSMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDSADNESSMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindSadnessMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindTirednessMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class USERSTATEOFMINDTIREDNESSMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_USERSTATEOFMINDTIREDNESSMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#UserStateOfMindTirednessMeasurableInformation"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#VelocityUnitContextParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VELOCITYUNITCONTEXTPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_VELOCITYUNITCONTEXTPARAMETER = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#VelocityUnitContextParameter"));

    /* ***************************************************
     * Class http://localhost:9998/owl/get-knowledge-ontology#VideoCameraAvailableMeasurableInformation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VIDEOCAMERAAVAILABLEMEASURABLEINFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_VIDEOCAMERAAVAILABLEMEASURABLEINFORMATION = factory.getOWLClass(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#VideoCameraAvailableMeasurableInformation"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasAlternative
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASALTERNATIVE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASALTERNATIVE = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasAlternative"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasBasis
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBASIS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBASIS = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasBasis"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasConstraintRequirement
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONSTRAINTREQUIREMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONSTRAINTREQUIREMENT = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasConstraintRequirement"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasContextClass
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTCLASS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTCLASS = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasContextClass"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasContextInformation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTINFORMATION = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasContextInformation"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasContextInformationParameter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXTINFORMATIONPARAMETER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXTINFORMATIONPARAMETER = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasContextInformationParameter"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasExtension
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASEXTENSION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASEXTENSION = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasExtension"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasFeature
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASFEATURE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASFEATURE = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasFeature"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasHelp
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASHELP.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASHELP = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasHelp"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasLearningUnitClass
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLEARNINGUNITCLASS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLEARNINGUNITCLASS = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasLearningUnitClass"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasMeasurableContextInformation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMEASURABLECONTEXTINFORMATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMEASURABLECONTEXTINFORMATION = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasMeasurableContextInformation"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasMetaData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMETADATA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMETADATA = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasMetaData"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasNotLearningUnitClass
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASNOTLEARNINGUNITCLASS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASNOTLEARNINGUNITCLASS = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasNotLearningUnitClass"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasPrerequisite
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPREREQUISITE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPREREQUISITE = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasPrerequisite"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasReference
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASREFERENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASREFERENCE = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasReference"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasRelation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRELATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRELATION = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasRelation"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#hasVersion
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASVERSION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASVERSION = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasVersion"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isBasisOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISBASISOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISBASISOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isBasisOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isConstraintRequirementOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONSTRAINTREQUIREMENTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONSTRAINTREQUIREMENTOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isConstraintRequirementOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isContextClassOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTCLASSOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTCLASSOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isContextClassOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isContextInformationOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTINFORMATIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTINFORMATIONOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isContextInformationOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isContextInformationParameterOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTINFORMATIONPARAMETEROF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTINFORMATIONPARAMETEROF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isContextInformationParameterOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isExtensionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISEXTENSIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISEXTENSIONOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isExtensionOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isFeatureOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISFEATUREOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISFEATUREOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isFeatureOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isHelpOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISHELPOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISHELPOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isHelpOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isLearningUnitClassOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISLEARNINGUNITCLASSOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISLEARNINGUNITCLASSOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isLearningUnitClassOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isMeasurableContextInformationOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISMEASURABLECONTEXTINFORMATIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISMEASURABLECONTEXTINFORMATIONOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isMeasurableContextInformationOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isMetaDataOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISMETADATAOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISMETADATAOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isMetaDataOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isPrerequisiteOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPREREQUISITEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPREREQUISITEOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isPrerequisiteOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isReferenceOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISREFERENCEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISREFERENCEOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isReferenceOf"));

    /* ***************************************************
     * Object Property http://localhost:9998/owl/get-knowledge-ontology#isVersionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISVERSIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISVERSIONOF = factory.getOWLObjectProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isVersionOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL_TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasAcquisitionDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASACQUISITIONDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASACQUISITIONDATE = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasAcquisitionDate"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasAgeLimit
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASAGELIMIT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASAGELIMIT = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasAgeLimit"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasAuthor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASAUTHOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASAUTHOR = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasAuthor"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasContentType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCONTENTTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCONTENTTYPE = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasContentType"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasDataType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDATATYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDATATYPE = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasDataType"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasDescription
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDESCRIPTION = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasDescription"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasDifficulty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDIFFICULTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDIFFICULTY = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasDifficulty"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasEndTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASENDTIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASENDTIME = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasEndTime"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasIdentifier
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASIDENTIFIER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASIDENTIFIER = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasIdentifier"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasInteractivity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASINTERACTIVITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASINTERACTIVITY = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasInteractivity"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasKeyword
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASKEYWORD.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASKEYWORD = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasKeyword"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasLID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLID = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasLID"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasLanguage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLANGUAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLANGUAGE = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasLanguage"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasLogicalOperator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLOGICALOPERATOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLOGICALOPERATOR = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasLogicalOperator"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasMetaData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASMETADATA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASMETADATA = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasMetaData"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAME = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasName"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasNavigationType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAVIGATIONTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAVIGATIONTYPE = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasNavigationType"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasStartingTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSTARTINGTIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSTARTINGTIME = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasStartingTime"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasSubject
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSUBJECT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSUBJECT = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasSubject"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasTrigger
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASTRIGGER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASTRIGGER = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasTrigger"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUE = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasValue"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasValueOperator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUEOPERATOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUEOPERATOR = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasValueOperator"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#hasVersionDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVERSIONDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVERSIONDATE = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#hasVersionDate"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#isRequired
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISREQUIRED.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISREQUIRED = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isRequired"));

    /* ***************************************************
     * Data Property http://localhost:9998/owl/get-knowledge-ontology#isScreenReaderSuitable
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISSCREENREADERSUITABLE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISSCREENREADERSUITABLE = factory.getOWLDataProperty(IRI.create("http://localhost:9998/owl/get-knowledge-ontology#isScreenReaderSuitable"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OWL_TOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
