package de.unipotsdam.rulegenerator.ontology.impl;

import de.unipotsdam.rulegenerator.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultRankingConstraintRequirement <br>
 * @version generated on Mon Feb 09 12:46:06 CET 2015 by tobias
 */
public class DefaultRankingConstraintRequirement extends WrappedIndividualImpl implements RankingConstraintRequirement {

    public DefaultRankingConstraintRequirement(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
