package de.unipotsdam.rulegenerator.ontology.impl;

import de.unipotsdam.rulegenerator.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultConstraint <br>
 * @version generated on Tue Sep 02 15:45:18 CEST 2014 by tobias
 */
public class DefaultConstraint extends WrappedIndividualImpl implements Constraint {

    public DefaultConstraint(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
