package de.unipotsdam.rulegenerator.ontology.impl;

import de.unipotsdam.rulegenerator.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultNavigationTypeMetaData <br>
 * @version generated on Tue Aug 19 13:30:58 CEST 2014 by tobias
 */
public class DefaultNavigationTypeMetaData extends WrappedIndividualImpl implements NavigationTypeMetaData {

    public DefaultNavigationTypeMetaData(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
