package de.unipotsdam.rulegenerator.ontology.impl;

import de.unipotsdam.rulegenerator.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultLearningUnitClassConstraint <br>
 * @version generated on Fri Oct 24 10:22:17 CEST 2014 by tobias
 */
public class DefaultLearningUnitClassConstraint extends WrappedIndividualImpl implements LearningUnitClassConstraint {

    public DefaultLearningUnitClassConstraint(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
