package de.unipotsdam.rulegenerator.ontology.impl;

import de.unipotsdam.rulegenerator.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTechnicalContext <br>
 * @version generated on Tue Aug 19 12:47:02 CEST 2014 by tobias
 */
public class DefaultTechnicalContext extends WrappedIndividualImpl implements TechnicalContext {

    public DefaultTechnicalContext(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
