package de.unipotsdam.rulegenerator.ontology.impl;

import de.unipotsdam.rulegenerator.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTemperatureScaleContextParameter <br>
 * @version generated on Wed Aug 27 13:57:18 CEST 2014 by tobias
 */
public class DefaultTemperatureScaleContextParameter extends WrappedIndividualImpl implements TemperatureScaleContextParameter {

    public DefaultTemperatureScaleContextParameter(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
