package de.unipotsdam.rulegenerator.ontology.impl;

import de.unipotsdam.rulegenerator.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultPersonalContext <br>
 * @version generated on Wed Sep 03 10:59:34 CEST 2014 by tobias
 */
public class DefaultPersonalContext extends WrappedIndividualImpl implements PersonalContext {

    public DefaultPersonalContext(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
