package de.unipotsdam.rulegenerator.ontology.impl;

import de.unipotsdam.rulegenerator.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultLearningUnitClassConstraint <br>
 * @version generated on Wed Aug 27 13:57:18 CEST 2014 by tobias
 */
public class DefaultLearningUnitClassConstraint extends WrappedIndividualImpl implements LearningUnitClassConstraint {

    public DefaultLearningUnitClassConstraint(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasLearningUnitConstraintMetaDataLogicalOperator
     */
     
    public Collection<? extends Object> getHasLearningUnitConstraintMetaDataLogicalOperator() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLEARNINGUNITCONSTRAINTMETADATALOGICALOPERATOR, Object.class);
    }

    public boolean hasHasLearningUnitConstraintMetaDataLogicalOperator() {
		return !getHasLearningUnitConstraintMetaDataLogicalOperator().isEmpty();
    }

    public void addHasLearningUnitConstraintMetaDataLogicalOperator(Object newHasLearningUnitConstraintMetaDataLogicalOperator) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLEARNINGUNITCONSTRAINTMETADATALOGICALOPERATOR, newHasLearningUnitConstraintMetaDataLogicalOperator);
    }

    public void removeHasLearningUnitConstraintMetaDataLogicalOperator(Object oldHasLearningUnitConstraintMetaDataLogicalOperator) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLEARNINGUNITCONSTRAINTMETADATALOGICALOPERATOR, oldHasLearningUnitConstraintMetaDataLogicalOperator);
    }


    /* ***************************************************
     * Data Property http://www.motivate-project.de/ontologies/knowledge#hasLearningUnitConstraintRequirementLogicalOperator
     */
     
    public Collection<? extends Object> getHasLearningUnitConstraintRequirementLogicalOperator() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLEARNINGUNITCONSTRAINTREQUIREMENTLOGICALOPERATOR, Object.class);
    }

    public boolean hasHasLearningUnitConstraintRequirementLogicalOperator() {
		return !getHasLearningUnitConstraintRequirementLogicalOperator().isEmpty();
    }

    public void addHasLearningUnitConstraintRequirementLogicalOperator(Object newHasLearningUnitConstraintRequirementLogicalOperator) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLEARNINGUNITCONSTRAINTREQUIREMENTLOGICALOPERATOR, newHasLearningUnitConstraintRequirementLogicalOperator);
    }

    public void removeHasLearningUnitConstraintRequirementLogicalOperator(Object oldHasLearningUnitConstraintRequirementLogicalOperator) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLEARNINGUNITCONSTRAINTREQUIREMENTLOGICALOPERATOR, oldHasLearningUnitConstraintRequirementLogicalOperator);
    }


}
