package de.unipotsdam.rulegenerator.ontology.impl;

import de.unipotsdam.rulegenerator.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTargetTimestampContextParameter <br>
 * @version generated on Thu Dec 04 13:00:54 CET 2014 by tobias
 */
public class DefaultTargetTimestampContextParameter extends WrappedIndividualImpl implements TargetTimestampContextParameter {

    public DefaultTargetTimestampContextParameter(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
